name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Dependencies
        run: nix-shell --run "make deps"

      - name: Compile
        run: |
          nix-shell --run "elm make --output=/dev/null src/Main.elm"
          nix-shell --run "cd review && elm make src/ReviewConfig.elm"
          nix-shell --run "make compile-ts"
      - name: Format
        run: |
          nix-shell --run "elm-format src/ review/ tests/ --validate"
          nix-shell --run "yarn prettier src/ --check"
      - name: Lint
        run: nix-shell --run "make lint"

      - name: Unit Tests
        run: nix-shell --run "make test"

      - name: Build
        run: nix-shell --run "make build"
